# Generated by Django 4.1.4 on 2022-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('stock_img', models.ImageField(upload_to='C:\\Users\\Kalyibek\\PycharmProjects\\INAI\\med_srs\\media\\stock_images')),
                ('proc_img', models.ImageField(upload_to='C:\\Users\\Kalyibek\\PycharmProjects\\INAI\\med_srs\\media\\processed_images')),
                ('type', models.CharField(choices=[('heart', 'сердце'), ('lungs', 'легкие'), ('stomach', 'желудок'), ('liver', 'печень'), ('kidneys', 'почки')], max_length=100)),
                ('posted_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
