# Generated by Django 4.1.4 on 2022-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_proc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medimage',
            name='proc_img',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Kalyibek\\PycharmProjects\\INAI\\med_srs\\media\\processed_images'),
        ),
    ]
