# Generated by Django 4.1.4 on 2022-12-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_proc', '0003_remove_medimage_proc_img_processedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='med_img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proc_img', to='image_proc.medimage'),
        ),
    ]
